### ISSUE TITLE
Shell script file list is not consistent

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#603]
**Describe the bug**
Shell scripts linting tools support different shell scripting languages, not just Bash.

The current (super-linter v3.8.0) mechanism has the following issues:

1. Assumes bash only (Example: the `VALIDATE_BASH` variable).
1. Has two mechanisms to check if a file is a shell script, and both are unreliable:
    1. Use the `file` utility, and check if the output of `file` matches a given string for Bash scripts.
    1. Check if a file extension is `sh`, and warn the user if `file` reports a shell script and the extension is not `sh`.

Both mechanisms have issues:

1. Linters such as `shellcheck` support multiple shells, not just bash.
1. There are perfectly valid use cases where shell don't need a `sh` extension.
1. It's impossible to exclude a given shell, such as ZSH, when it's not supported by one of the linters.

**To Reproduce**
Lint a code base with ZSH scripts, for example.

**Expected behavior**
Ideas to fix the issue: inspect the shell script hash-bang, instead of relying on the `file` utility, or the file extension. Example, to get all Bourne, Bash, and KSH shell scripts, excluding ZSH scripts:

```shell
^#!(.*/|.*env +)(sh|bash|ksh)
```

Some ideas for a longer-term plan:

1. Treat shell scripting languages as a distinct languages. Example: bash is a language, ZSH is a language, KSH is a language...
1. Treat all the Linux shell scripting languages as a single language, and rely on the configuration of specific linters. Example: tune the suggested regex to include all the possible hash-bangs, then configure specific linters, such as `shellcheck`, to instruct them on what to do with each script type.

**Screenshots**
Example of an attempt of linting a codebase that contains an (unsupported) ZSH script with shellcheck:

```shell
In /workspace/.shells/.zsh/login.sh line 1:
#!/usr/bin/env zsh
^-- SC1071: ShellCheck only supports sh/bash/dash/ksh scripts. Sorry!
```

**Comment by ferrarimarco** [comment]
I'm still looking for a ZSH one.

The thing is that with the current configuration, it's not possible to exclude ZSH scripts from being linted with shellcheck for the reasons I stated above :(

**Comment by ferrarimarco** [comment]
@admiralAwkbar I tried super-linter v3.8.3, but ZSH scripts are not excluded :(

Example:

```shell
#!/usr/bin/env zsh

# shellcheck source=/dev/null
. "$HOME"/.shells/.all/logout.sh
```

`file` reports: `.shells/.zsh/logout.sh: Paul Falstad's zsh script, ASCII text executable`

**Comment by admiralAwkbar** [comment]
@ferrarimarco i will do some additional testing.. that's super odd

**Comment by ferrarimarco** [comment]
@admiralAwkbar shall we reopen this issue as a reminder? Thanks!

**Comment by admiralAwkbar** [comment]
@ferrarimarco The issue was someone deleted the underlying libs to check a file on the super linter
it should be working as of 2.8.3
can you validate?

**Comment by ferrarimarco** [comment]
Validated! I assume you meant v3.8.3. I don't see the issue anymore! Thanks!

**Comment by ferrarimarco** [comment]
@admiralAwkbar sorry, I spoke too soon! Even with v3.8.3 the issue is still not fixed :(

**Comment by ferrarimarco** [comment]
@admiralAwkbar I think I know what's happening. The fix in #609 applies only when you call `BuildFileList`, which is not the case if you set `VALIDATE_ALL_CODEBASE` to `true` (directly, or via `RUN_LOCAL`).
