### ISSUE TITLE
Files are not linted when run in Azure Devops pipeline

### ISSUE THREAD

**Issue by prabhakarreddy1234** [github/super-linter#813]
**Describe the bug**
I added super-linter step to a build pipeline in azure devops. When the pipeline is run, lint step is simply ignoring all the files in the working directory. I written `ls` on working directory to console. It shows all the files. Attached logs.

```
2020-10-07T13:41:41.1967635Z ##[section]Starting: Lint Target Files
2020-10-07T13:41:41.1977543Z ==============================================================================
2020-10-07T13:41:41.1978015Z Task         : Command line
2020-10-07T13:41:41.1978500Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2020-10-07T13:41:41.1978948Z Version      : 2.164.2
2020-10-07T13:41:41.1979322Z Author       : Microsoft Corporation
2020-10-07T13:41:41.1979848Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2020-10-07T13:41:41.1980563Z ==============================================================================
2020-10-07T13:41:41.5695011Z Generating script.
2020-10-07T13:41:41.5717652Z ========================== Starting Command Output ===========================
2020-10-07T13:41:41.5759537Z [command]/bin/bash --noprofile --norc /__w/_temp/f3470404-8a40-4348-8609-b8a412e34937.sh
2020-10-07T13:41:41.5843650Z /__w/2/s/azure-dotnet/framework/devops/
2020-10-07T13:41:41.5871212Z pipelines
2020-10-07T13:41:41.5872210Z scripts
2020-10-07T13:41:41.5887437Z build-framework.yml
2020-10-07T13:41:41.5888471Z deploy-framework.yml
2020-10-07T13:41:41.5889632Z job-build-code-analysis.yml
2020-10-07T13:41:41.5890648Z job-build-nexus.yml
2020-10-07T13:41:41.5892166Z job-build-run-***s.yml
2020-10-07T13:41:41.5893263Z job-build-solution.yml
2020-10-07T13:41:41.5894238Z job-build-sonar.yml
2020-10-07T13:41:41.5895385Z job-build-***s.yml
2020-10-07T13:41:41.5896219Z job-deploy-databases.yml
2020-10-07T13:41:41.5897186Z tasks-connect-azure-subscription.yml
2020-10-07T13:41:41.5898092Z tasks-migrate-database.yml
2020-10-07T13:41:42.8420544Z la***: Pulling from github/super-linter
2020-10-07T13:41:42.8430758Z Digest: sha256:975b109051933fe6da1f87f9b83ce65c18af4b43238fab61be908b16552919bb
2020-10-07T13:41:42.8432579Z Status: Image is up to date for github/super-linter:la***
2020-10-07T13:41:42.8448967Z docker.io/github/super-linter:la***
2020-10-07T13:41:43.2356040Z --------------------------------------------------------------------------------
2020-10-07T13:41:43.2358110Z 
2020-10-07T13:41:43.2358725Z                               /@@#///////@@/(@//@%/(@.@(       @@
2020-10-07T13:41:43.2359537Z                           @@//////////////////////////////#*  @@@
2020-10-07T13:41:43.2360199Z                         @////@//(///////////@@@@@///@//@/@**//@@(
2020-10-07T13:41:43.2360671Z                       @///////@///////////////@@@@    (           @,
2020-10-07T13:41:43.2361150Z                      @/(&/@////////////////////                     @
2020-10-07T13:41:43.2361657Z                     @////////////////////////@@                      @
2020-10-07T13:41:43.2362189Z                   @%////////(//////////%/////&@            @@       *,@           ______________
2020-10-07T13:41:43.2362764Z              @@@@@/@/#/////(&//////////////////                       .@         /              \
2020-10-07T13:41:43.2363671Z         *@@@@@.    .%///(//@//////////////////&.   .@@,                 @%      / Don't mind me  \
2020-10-07T13:41:43.2364513Z       @@%           .&@&&/@.@//&/////(//////////    @@@@@@@@@         .. &@    / I'm just looking \
2020-10-07T13:41:43.2365106Z     @@%               @@@@@   @&/////////////////#   @/       V  @@/ ,@@@ @   <  for some trash... |
2020-10-07T13:41:43.2366011Z @@@%                   @@@@        .%@@@@//////#@ @   @@         @     .,.     \__________________/
2020-10-07T13:41:43.2366554Z                                           @@@/@(  (@@@@% @/\      %
2020-10-07T13:41:43.2367023Z                                            @@@@(    .     .@@/\   #
2020-10-07T13:41:43.2367483Z                                              @                  %@%
2020-10-07T13:41:43.2367748Z 
2020-10-07T13:41:43.2368415Z --------------------------------------------------------------------------------
2020-10-07T13:41:43.2387871Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   ---------------------------------------------[0m
2020-10-07T13:41:43.2416004Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   --- GitHub Actions Multi Language Linter ----[0m
2020-10-07T13:41:43.2443106Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m    - Image Creation Date:[2020-10-06T17:50:35Z][0m
2020-10-07T13:41:43.2475223Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m    - Image Revision:[30bbf89][0m
2020-10-07T13:41:43.2502248Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m    - Image Version:[la***][0m
2020-10-07T13:41:43.2530877Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   ---------------------------------------------[0m
2020-10-07T13:41:43.2561394Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   ---------------------------------------------[0m
2020-10-07T13:41:43.2590937Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   The Super-Linter source code can be found at:[0m
2020-10-07T13:41:43.2622070Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m    - https://github.com/github/super-linter[0m
2020-10-07T13:41:43.2650831Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   ---------------------------------------------[0m
2020-10-07T13:41:43.2680493Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   --------------------------------------------[0m
2020-10-07T13:41:43.2709128Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   Gathering GitHub information...[0m
2020-10-07T13:41:43.2739300Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   NOTE: ENV VAR [RUN_LOCAL] has been set to:[true][0m
2020-10-07T13:41:43.2769075Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   bypassing GitHub Actions variables...[0m
2020-10-07T13:41:43.2799483Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   Linting all files in mapped directory:[/tmp/lint][0m
2020-10-07T13:41:43.2828166Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   Successfully found:[0;37m[GITHUB_TOKEN][0m
2020-10-07T13:41:43.2859505Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   --------------------------------------------[0m
2020-10-07T13:41:43.2889957Z [0m2020-10-07 13:41:43 [0;34m[INFO  ][0m   Gathering user validation information...[0m
2020-10-07T13:41:44.1877465Z [0m2020-10-07 13:41:44 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-10-07T13:41:44.1907999Z [0m2020-10-07 13:41:44 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-10-07T13:41:44.1940418Z [0m2020-10-07 13:41:44 [0;34m[INFO  ][0m   Generated reports:[0m
2020-10-07T13:41:44.1969943Z [0m2020-10-07 13:41:44 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-10-07T13:41:44.2002723Z [0m2020-10-07 13:41:44 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-10-07T13:41:44.2035072Z [0m2020-10-07 13:41:44 [0;34m[INFO  ][0m   Reports generated in folder /tmp/lint/super-linter.report[0m
2020-10-07T13:41:44.2066659Z [0m2020-10-07 13:41:44 [0;33m[WARN  ][0m   Report output folder (/tmp/lint/super-linter.report) does NOT exist.[0m
2020-10-07T13:41:44.2099029Z [0m2020-10-07 13:41:44 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-10-07T13:41:44.2128571Z [0m2020-10-07 13:41:44 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-10-07T13:41:44.2159912Z [0m2020-10-07 13:41:44 [0;34m[INFO  ][0m   The script has completed[0m
2020-10-07T13:41:44.2192037Z [0m2020-10-07 13:41:44 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-10-07T13:41:44.2224581Z [0m2020-10-07 13:41:44 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-10-07T13:41:44.2323204Z [0m2020-10-07 13:41:44 [0;32m[NOTICE][0m   All file(s) linted successfully with no errors detected[0m
2020-10-07T13:41:44.2352178Z [0m2020-10-07 13:41:44 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-10-07T13:41:44.4768835Z 
2020-10-07T13:41:44.5234472Z ##[section]Finishing: Lint Target Files
```

**To Reproduce**

1. Add below step to any build pipeline job.
```
  - job: lint_tests
    displayName: Lint Tests
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        docker pull github/super-linter:latest
        docker run -e RUN_LOCAL=true -e VALIDATE_YAML=true -v $(System.DefaultWorkingDirectory):/tmp/lint github/super-linter
      displayName: 'Code Scan using GitHub Super-Linter'
```

**Expected behavior**
It should lint all the files in the directory and return output

**Comment by omusavi** [comment]
One thing I have found can be helpful is to add the super-linter.log file as a build artifact, there is a lot more information there that can help debug the issue

**Comment by GaboFDC** [comment]
Maybe in the pipeline the tmp dir is not being mounted correctly? I assume that the `ls` you did was on System.DefaultWorkingDirectory, but maybe the container is not getting it? I'm not able to test this, but if you provide a more detailes like as @omusavi said an also if you run with `LOG_LEVEL=TRACE` and `ACTIONS_RUNNER_DEBUG=true` to see all possible details

**Comment by admiralAwkbar** [comment]
@prabhakarreddy1234 just pushed new code to latest can you try to run again and see if no files are found in the mount?

**Comment by GaboFDC** [comment]
@prabhakarreddy1234 please run with LOG_LEVEL=TRACE and ACTIONS_RUNNER_DEBUG=true to see all possible details, to facilitate the debug.

**Comment by prabhakarreddy1234** [comment]
Thanks @GaboFDC 

Logs are attached.  Somehow all files are `Excluded`. Please let me know if you find anything.

[lint-logs.txt](https://github.com/github/super-linter/files/5409983/lint-logs.txt)

**Comment by GaboFDC** [comment]
@prabhakarreddy1234 unfortunatelly seems like that run was affected by #880 
Also note that the bash errors you mentions, the ones that start with `##[debug]` are not commig from super linter but from azure itself.
Could you do a test again?

**Comment by prabhakarreddy1234** [comment]
@GaboFDC 

Reran the pipeline. It downloaded `github/super-linter:latest` again. But same log output. It couldn't find any files.

**Comment by GaboFDC** [comment]
@prabhakarreddy1234 that is weird, on latest log, the problem i saw was on:

```
2020-10-20T16:01:06.7306968Z [0m2020-10-20 16:01:06 [0;34m[DEBUG ][0m   ----------------------------------------------[0m
2020-10-20T16:01:06.7336360Z [0m2020-10-20 16:01:06 [0;34m[DEBUG ][0m   Populating the file list with all the files in the /tmp/lint/.automation/test workspace[0m
2020-10-20T16:01:06.7381004Z [0m2020-10-20 16:01:06 [0;34m[INFO  ][0m   ---------------------------------[0m
2020-10-20T16:01:06.7413477Z [0m2020-10-20 16:01:06 [0;34m[INFO  ][0m   ------ File list to check: ------[0m
2020-10-20T16:01:06.7443599Z [0m2020-10-20 16:01:06 [0;34m[INFO  ][0m   ---------------------------------[0m
2020-10-20T16:01:06.7491130Z [0m2020-10-20 16:01:06 [0;34m[DEBUG ][0m   File:[find: /tmp/lint/.automation/test: No such file or directory], File_type:[automation/test: no such file or directory], Base_file:[test: no such file or directory][0m
```

Seems like is trying to get the files fdrom the .automation folder, this was a but, but was fixed already

**Comment by prabhakarreddy1234** [comment]
@GaboFDC  I am sure it pulled latest super-linter image. I can specify the tag to be sure of pulling the latest fixes. Can you give me the tag please?

**Comment by prabhakarreddy1234** [comment]
@GaboFDC  I'm still facing the issue with `latest` tag. Is there anything i need to try ?

**Comment by prabhakarreddy1234** [comment]
@GaboFDC is there anything else i can try to make it work?

**Comment by GaboFDC** [comment]
Could you share latest logs again? the debug log have improved a bit recently, and we may find now the error

**Comment by prabhakarreddy1234** [comment]
@GaboFDC  Yea. debug log is improved a lot. Thanks. Attached the logs.[
[logs (1).txt](https://github.com/github/super-linter/files/5617401/logs.1.txt)
](url)

**Comment by GaboFDC** [comment]
In the logs is not shown how the container is started, could you show this?

**Comment by prabhakarreddy1234** [comment]
The logs shows starting from `github/super-linter` image download to running the lint. It shows all environment variables etc.  Which container logs you want?

**Comment by GaboFDC** [comment]
Again, this just seems like the files are not present on the container.
You could verify it by running:

```
docker run -e RUN_LOCAL=true -e LOG_LEVEL=TRACE -e ACTIONS_RUNNER_DEBUG=true -e VALIDATE_TERRAFORM=true -e VALIDATE_YAML=true -v $(Lint-Target-Directory):/tmp/lint --entrypoint "ls" github/super-linter  /tmp/lint/ -lha
```
